### ISSUE TITLE
Comment name property for first comment fails if no file level comment

### ISSUE THREAD

**Issue by danoc** [optimizely/scribesass-parser#15]
This would not return the name of the first annotation unless a file-level comment is added.

``` scss
/// Compass polyfills
/// @description Line 1
/// Line 2!
.foo {
  color: red;
}

/// One more comment?
.bar {
  color: blue;
}
```
